# Generated by Django 4.1.6 on 2023-03-09 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tquiper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='empresa',
            new_name='company',
        ),
    ]
