# Generated by Django 4.1.6 on 2023-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0002_rename_account_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
