# Generated by Django 4.1.6 on 2023-03-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0004_company_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Tquipers', 'verbose_name_plural': 'Tquiper'},
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Tquiper.category'),
        ),
    ]
