# Generated by Django 4.1.6 on 2023-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0006_person_rename_category_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
    ]
