# Generated by Django 4.1.6 on 2023-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0009_rename_first_name_company_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Dados Empresariais', 'verbose_name_plural': 'Dados Empresariais'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Contrato_Imagem',
            new_name='Imagem_do_Contrato',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Quando_foi_gasto',
            new_name='Valor_Gasto',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='DateTimeField',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Grupo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Funcionario'), ('Company', 'Empresa')], default='Company', max_length=100),
        ),
    ]
