# Generated by Django 4.1.6 on 2023-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0010_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='DateTimeField',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
