# Generated by Django 4.1.6 on 2024-11-05 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0002_rename_account_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_profissional', models.CharField(max_length=50, verbose_name='Categoria Profissional')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R$ Mês')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SubTotal Por')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_direct_entries', to='Tquiper.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LaborDirectHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateTimeField(verbose_name='Data de Registro')),
                ('labor_direct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Tquiper.labordirect')),
            ],
        ),
    ]
