# Generated by Django 4.1.6 on 2024-11-05 01:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0003_empresa_labordirect_labordirecthistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborIndirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_profissional', models.CharField(max_length=50, verbose_name='Categoria Profissional')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R$ Mês')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SubTotal Por')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_indirect_entries', to='Tquiper.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OutrosBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_profissional', models.CharField(max_length=50, verbose_name='Categoria Profissional')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('plr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PRL (%)')),
                ('pts', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PTS (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SubTotal (R$ Mês)')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_beneficios_entries', to='Tquiper.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OutrosBeneficiosHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('plr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateTimeField(verbose_name='Data de Registro')),
                ('outros_beneficios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Tquiper.outrosbeneficios')),
            ],
        ),
        migrations.CreateModel(
            name='LaborIndirectHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateTimeField(verbose_name='Data de Registro')),
                ('labor_indirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Tquiper.laborindirect')),
            ],
        ),
    ]
