# Generated by Django 4.1.6 on 2024-11-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tquiper', '0004_laborindirect_outrosbeneficios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site da Empresa'),
        ),
    ]
